language: ruby
env:
  - USE_OFFICIAL_GEM_SOURCE=1
  - COVERAGE=true

services:
  - mysql
  - redis-server

rvm:
  - 2.3.4
  - 2.4.1

sudo: true
dist: trusty

before_script:
  # To resolve: Mysql2::Error: Specified key was too long; max key length is 767 bytes
  - echo '[mysqld]' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_file_format=Barracuda' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_file_per_table=1' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - echo 'innodb_large_prefix=1' | sudo sh -c 'cat >>  /etc/mysql/my.cnf'
  - sudo service mysql restart
  - mysql -e 'create database poker_test charset utf8;'
  - cp config/database.yml.template config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - cd client && yarn && yarn run test
  - cd ..

before_install:
  - nvm install node
  # - bundle install --full-index

script: RAILS_ENV=test bundle exec rspec
cache: bundler
cache: yarn