language: ruby
env:
  - USE_OFFICIAL_GEM_SOURCE=1
  - COVERAGE=true

services:
  - postgresql
  - redis-server

rvm:
  - 2.3.4
  - 2.4.1
  - 2.5.1

sudo: true
dist: trusty

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d "travis_ci_test" -U postgres -c "create extension pg_trgm"
  - cp config/database.yml.template config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - cd client && yarn && yarn run test
  - cd ..

before_install:
  - nvm install node
  # - bundle install --full-index

script: RAILS_ENV=test bundle exec rspec
cache: bundler
cache: yarn
