google:
  key: blah
  secret: blah

github:
  key: blah
  secret: blah

weibo:
  key: blah
  secret: blah
  redirect_uri: http://a3.dev:3000/users/auth/weibo/callback

facebook:
  key: blah
  secret: blah

twitter:
  key: blah
  secret: blah