# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 080cc4f19a697b08b5c7217117fd5e9f7b771f02c90a08e208196798d6ad716280ede336c76eb7fef7102076527135b6f5fa918943183290e8146d286f20fbff

test:
  secret_key_base: d8b0388fee26acc99a4276dc546eae30c655c3932022728baef0cc33e5da8dd68b2a43be153499e40171ed3451d3365be5b0b6ba58103c92fb2ebb4389a58585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
