---
#pid: tmp/pids/thin.8888.pid
#port: 8888
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 3
threaded: false
daemonize: true
socket: /tmp/thin.sock
# #tag: a-name-to-show-up-in-ps aux